#define ENABLE_CLOCK_MOUDLE         0
#define ENABLE_LCD_MOUDLE           0
#define ENABLE_LED_MOUDLE           0
#define ENABLE_UART_MOUDLE          0
#define ENABLE_INTERRUPY_MOUDLE     0
#define ENABLE_NV_FALSH_MOUDLE      0
#define ENABLE_TEMPERATURE_MOUDLE   0
#define ENABLE_RTXOS_MOUDLE         0
#define ENABLE_DHT11_MOUDLE         0
#define ENABLE_TFT_MOUDLE           0